### ISSUE TITLE
Bug: IMU orientation wrong, no pitch response, only roll (frame misaligned?)

### ISSUE THREAD

**Issue by DWDROME** [WITMOTION/WitHighModbus_HWT9073485#4]
https://github.com/user-attachments/assets/22328183-f8e3-44c2-9e7f-43846ffeb612

#### Description

When using the `witmotion_imu_ros2` package, the IMU publishes both `/imu/data` and `/imu/mag`, but there are multiple issues:

- `linear_acceleration_covariance` and `magnetic_field_covariance` are all set to zero.
- Magnetic field data is always `[0.0, 0.0, 0.0]`, which may mislead downstream filters.
- In RViz, when the sensor is tilted forward/backward (pitch), **only the X-axis rotates (roll)**, indicating a frame misalignment.
- The TF frame is set to `base_link`, but appears to violate standard ROS REP-103 coordinate conventions.

---

#### Sample Data

```yaml
linear_acceleration:
  x: 0.7034
  y: -0.5407
  z: 9.7904
linear_acceleration_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

magnetic_field:
  x: 0.0
  y: 0.0
  z: 0.0
magnetic_field_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
```

---

#### Environment

- ROS distro: `Noetic` / `ROS 2 Humble`
- IMU Model: WT901 (Modbus)
- Driver: witmotion_imu_ros2 (from GitHub)

---

#### Possible Cause

- The orientation quaternion may have been computed using an incorrect axis order (e.g., wrong order of `quaternion_from_euler()`).
- IMU frame might not have been aligned to ROS standards (`+Z up`, `+X forward`, `+Y left`).
- Magnetic data may be uninitialized or unsupported by the sensor model.

---

#### Suggestion

- Apply a configurable static transform if needed (e.g., `static_transform_publisher`) to align IMU axes.
- Replace covariance with a default (e.g., `0.01` for diagonal) instead of zero.
- Skip `magnetic_field` topic if no valid data is provided.
